### ISSUE TITLE
Investigate platforms for running a permitify-based demo

### ISSUE THREAD

**Issue by swcurran** [bcgov/greenlight#120]
Investigate how best to run a Permitify-based demo in a workshop environment.  Ideally, the platform would be browser-based so we would not have to pre-announce prerequisites for the workshop (like git, docker, etc).  Investigate: learn.openshift.com and the platform provider that it use - katacoda.

In selecting a platform, define what we will have to put in place to run on the platform (e.g. shell scripts, browsers, etc.).

NOTE: git and github *might* be reasonable pre-requisites.  Docker running locally is a harder one.

**Comment by swcurran** [comment]
Resolved.  Here is the approach we will use:

* von-network will be using a Digital Ocean node set (likely: http://159.89.115.24/)
* TOB will be running in OpenShift - either permitify dev or test (or even prod, I guess)
* A set of companies will be pre-loaded into the environments

Users will use Play With Docker (https://labs.play-with-docker.com/) to get a copy of the von-ivy repo and use whatever instructions are provided to:

- find the genesis file for the indy network
- find the instance of TOB
- define a schema
- define a mapping
- optional - define a proof request
- set a colour for their service web page
- define a an icon


Once minimally configured, they can bring up their service and begin issuing credentials.  They can optionally reference other credentials in their proof request - either ones from permitify services or from others around them in the workshop.

**Comment by WadeBarnes** [comment]
Regarding the TOB Demo environments connected/connecting to Permitify.  Depending on timing you'll want to use `dev` (`devex-von-dev` to be specific), `test` (`devex-von-test`) is currently not compatible (it needs to be upgraded), and there is no (never has been a) TOB instance deployed to `prod` (`devex-von-prod`).

You'll want to use the matching BCovrin Ledger for the environment, for consistency `dev` (http://159.89.115.24/), or `test` (http://138.197.138.255/) assuming TOB/Permitify are upgraded in `test` before the workshop.

**Comment by swcurran** [comment]
Wade - yes - we'll have to pick an environment for running the workshop. The reason I mention "prod" (or really, some arbitrary new environment) is that this is a new use that is different from "dev" (prep environment for "test") and "test" (the permitify dFlow and TheOrgBook Demo site). The Workshop will pollute test with extra Issuers (VON-IVy instances) and so would require a reset after running. That might be the way we go or we might like to have a place that people can play on their own after the workshop. Still to be decided...
