### ISSUE TITLE
Please change the name of the repo to greenlight

### ISSUE THREAD

**Issue by swcurran** [bcgov/greenlight#231]
@WadeBarnes - please change the repo name to greenlight and let us know when it is done. I'll make the updates to the various docs once that's done.  I assume you will also have to update various OpenShift scripts to make this happen - or at least make the changes soon after.

Thanks

**Comment by WadeBarnes** [comment]
Rename complete

**Comment by swcurran** [comment]
@WadeBarnes - back to you to deploy greenlight on OpenShift.  I ran a local test with docker-compose and it worked fine, but you need to verify it deploys on OpenShift as appropriate. Once done, please assign to Emilliano to load data.

@esune - this ticket will go to you after the deployment to load the test data into the OpenShift deployments.  I renamed the test data load folders and files, as well the schema names.

Note that I changed other repos (von-network, TheOrgBook, von-agent-template, von) but I don't think any of those have any test impacts.  I'll keep trying them to ensure there is no impact.

**Comment by esune** [comment]
@swcurran: @WadeBarnes and I agreed I'll get the new deployments going as well, so I can do everything at once.

**Comment by esune** [comment]
The environments have been refreshed and test was reloaded. All the URLs referencing `dflow` have been removed as now `greenlight` is the official name.

@jljordan42, @swcurran: the DNS entries pointing to `http://dev-dflow.orgbook.gov.bc.ca` and `http://dflow.orgbook.gov.bc.ca` can now be removed.
