### ISSUE TITLE
Address security alerts in package.json

### ISSUE THREAD

**Issue by swcurran** [bcgov/greenlight#234]
Bootstrap and tar.  See: https://github.com/bcgov/greenlight/network/alerts

**Comment by esune** [comment]
@swcurran can you please check whether the updates I made to GreenLight on Monday have addressed the security alerts and let me know?

**Comment by swcurran** [comment]
@esune as of now, the security alert is still displayed for tar.  I made you an admin on the repo, so you should be able to see it.  Link above is still showing the issue.
