### ISSUE TITLE
Error running ./manage start under docker

### ISSUE THREAD

**Issue by regovtech** [bcgov/greenlight#240]
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling caddy (greenlight:)...
ERROR: pull access denied for greenlight, repository does not exist or may require 'docker login'

**Comment by ianco** [comment]
I've noticed this error when I've deleted the docker images without removing the volumes (i.e. "./manage stop" followed by "docker rmi <images>"

Try doing a full cleanup ("./manage rm" in all shells) followed by "./manage build", and then try "./manage start" again ...
