### ISSUE TITLE
querystringify vulnerability

### ISSUE THREAD

**Issue by swcurran** [bcgov/greenlight#243]
We found a vulnerable dependency in a repository you have security alert access to.

@bcgov	bcgov/greenlight

Known high severity security vulnerability detected in querystringify > 2.0.0 defined in package-lock.json.
package-lock.json update suggested: querystringify ~> 2.0.0.

**Comment by esune** [comment]
@swcurran `querystringify` is already at a version including the fix for the vulnerability (2.1.1), and therefore the vulnerability alert is not showing in the repository.
