### ISSUE TITLE
Update caddy file to V2

### ISSUE THREAD

**Issue by itchison** [bcgov/greenlight#256]
The https://github.com/BCDevOps/s2i-caddy repo recently updated to Caddy V2. When using the latest code from this repo, caddy in greenlight complains about the log directive. I rolled the recent changes back in a forked repo and was able to stand up caddy in greenlight. My suspicion is this is a result in the upgrade to V2 or some other recent commits against bcdevops/s2i-caddy. IANACE (I am not a caddy expert) otherwise I might through a PR for the fix. Thanks!

**Comment by WadeBarnes** [comment]
Implemented a workaround; https://github.com/bcgov/greenlight/commit/ad63af2a8f35e30ee1d9b19e0b1e2635df26b6f4

**Comment by WadeBarnes** [comment]
We either need to update the Caddy config file to support the new version of Caddy, or mark the repo as archived since we don't have plans for a Hyperledger Aries implementation of tis demo.  Either way there is a decision that needs to be made.

**Comment by esune** [comment]
Project has reached end-of-life and will be archived.
